name: Tower-Escape
version: 0.1.0.0
github: "alejocp00/Tower-Escape"
license: MIT
author: "Alejandro Camacho Pérez"
maintainer: "alex00cu@gmail.com"
copyright: "2023 Alejandro Camacho Pérez"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/alejocp00/Tower-Escape#readme>

dependencies:
  - base >= 4.7 && < 5
  - gloss
  - random
  - pcg-random
  - JuicyPixels
  - gloss-juicy
  - yaml
  - process
  - GLUT

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  Tower-Escape-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Tower-Escape
      - gloss
      - random
      - pcg-random
      - gloss-juicy
      - JuicyPixels
      - process
      - yaml
      - GLUT

tests:
  Tower-Escape-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Tower-Escape
      - gloss
      - random
      - pcg-random
      - JuicyPixels
      - gloss-juicy
      - process
      - yaml
      - GLUT
